docs_dir: docs
site_dir: html/guide
site_name: p3-db
site_description: "A tiny PDO database abstraction layer"
nav:
    - "Home": index.md
    - "Db": db.md
    - "Sql":
        - "Elements": sql/elements.md
        - "Statements": sql/statements.md
        - "Drivers": sql/drivers.md
repo_url: 'https://github.com/pine3ree/p3-db'
theme: readthedocs
